### ISSUE TITLE
Poor GUID validity check

### ISSUE THREAD

**Issue by lundmikkel** [willemtoerien/ts-guid#1]
The isGuid method seems to allow much more than just GUIDs:
https://github.com/willemtoerien/ts-guid/blob/master/src/isGuid.ts#L11

Since the character range goes from A-Z, values between G-Z are incorrectly allowed. A better regex is suggested here: https://stackoverflow.com/a/11040993/234910. Be aware that it does allow more possible values though.

The tests also seems quite sparse. Using "nonsense" as the only invalid test string seems like a poor choice as well. Consider using invalid strings that closely represent actual GUIDs, but are invalid, like:

- 70d**g**bedd-bc4e-4547-b50c-be1bef04d488
- 70dcbedd-bc4e-**5**547-b50c-be1bef04d488
- 70dcbedd-bc4e-4547-b50c-be1bef04d48
- 70dcbeddbc4e4547b50cbe1bef04d488
- And so on.

**Comment by willemtoerien** [comment]
Thanks for the info. I'll have a look into it today or tomorrow and update it accordingly.

**Comment by willemtoerien** [comment]
Updated and published to 1.0.12
